blank_issues_enabled: true
contact_links:
  - name: Question
    url: https://github.com/microlam-io/microlam/issues/new/choose
    about: I want to open a issue about Microlam.
  - name: Question
    url: https://stackoverflow.com/questions/ask?tags=microlam
    about: I have a question about Microlam.
  - name: Microlam Zulip chat
    url: https://microlam.zulipchat.com/
    about: If you prefer live chat with the developers, we have a Zulip chat where we all hang out.
  - name: Microlam Development mailing list 
    url: https://groups.google.com/forum/#!forum/microlam-io
    about: You can also ask questions on our mailing list.
